PROGRAM SMALL_CODE_TWISS
USE MY_OWN_LITTLE_CODE_UTILITIES
IMPLICIT NONE
TYPE(MY_TAYLOR) Z(2),X,PHASE_ADVANCE,beta,gamma,alpha,ct
TYPE(MY_TAYLOR)  X2_AVERAGE,X_AVERAGE,X_AVERAGE_XP
TYPE(NORMALFORM) NORMAL
TYPE(MY_MAP) M,ID,A_CS,DISP,A_L,A_NL,A_TRACKED,A_2
REAL(DP) L,K1,FIX(3),MA(3,3),H,DX_AVERAGE_DJ,BETAX,ALPHAX
INTEGER I,N,MF,J,I1,I2,K,NST,MFM,j1(2),j2(2)
TYPE(MAGNET) :: LATTICE(6*10)
TYPE(RAY) R
epsclean=1.d-30
EPSPRINT=1.D-6
write(6,*) " give e1: 0 (normal quadrupole) or WM.INC secret value (0.25 for example)"
read(5,*) e1

!   MAD-X LATTICE
!   L : DRIFT, L= 1.0;
!   ALPHA= 0.314159265358979;
! QF : SBEND,L= 1.0, ANGLE=ALPHA,K1=1.0;   
! QD : SBEND,L= 1.0, ANGLE=ALPHA,K1=-1.0;   
!   SF  : SEXTUPOLE,  K2= 2.0;
!LATTICE : LINE=  10*(QF,SF,L,QD,SF,L);

WRITE(6,*) " CREATING THE SIMPLE LATTICE: 10*(QF,SF,L,QD,SF,L) "
NST=40
L=1.0_DP
H= TWOPI/20/L

DO I=1,10
 K=(I-1)*6
 LATTICE(1+K)%NAME="QF";LATTICE(1+K)%L=L;LATTICE(1+K)%BN=0.0_DP
 LATTICE(1+K)%bn(ptc_def+0)=H;LATTICE(1+K)%H=H;LATTICE(1+K)%bn(ptc_def+1)=1.0_DP;LATTICE(1+K)%N=NST
 
 LATTICE(2+K)%NAME="SF";LATTICE(2+K)%L=0.0_DP;LATTICE(2+K)%BN=0.0_DP
 LATTICE(2+K)%bn(ptc_def+2)=2.0_DP;LATTICE(2+K)%H=0;LATTICE(2+K)%N=0; !LATTICE(2+K)%bn(ptc_def+0)=0.02D0;
 
 LATTICE(3+K)%NAME="L";LATTICE(3+K)%L=1.0_DP;LATTICE(3+K)%BN=0.0_DP
 LATTICE(3+K)%H=0;LATTICE(3+K)%N=1 
 
 LATTICE(4+K)%NAME="QD";LATTICE(4+K)%L=L;LATTICE(4+K)%BN=0.0_DP
 LATTICE(4+K)%bn(ptc_def+1)=-1.0_DP;LATTICE(4+K)%bn(ptc_def+0)=H;LATTICE(4+K)%H=H
 LATTICE(4+K)%N=NST
 
 LATTICE(5+K)%NAME="SF";LATTICE(5+K)%L=0.0_DP;LATTICE(5+K)%BN=0.0_DP
 LATTICE(5+K)%bn(ptc_def+2)=2.0_DP;LATTICE(5+K)%H=0;LATTICE(5+K)%N=0
 
 LATTICE(6+K)%NAME="L";LATTICE(6+K)%L=1.0_DP;LATTICE(6+K)%BN=0.0_DP
 LATTICE(6+K)%H=0;LATTICE(6+K)%N=1
ENDDO
MF=16
OPEN(UNIT=MF,FILE="TWISS.TXT")
MFM=17
OPEN(UNIT=MFM,FILE="MAPS.TXT")
 WRITE(MF,'(A4,6X,A7,7X,3X,A15,3X,4X,A14,9X,A10,9X,A11)')  &
"NAME", "PHASE_X", "DPHASE_X/DDELTA","DPHASE_X/DR2_X","   BETA   ","   ALPHA   "
 WRITE(MF,*) " "
 

DELTA_IS_3RD_PARAMETER=.TRUE.

ORDER_OF_TAYLOR=3

FIX=0.0_DP  ! FIXED POINT
CALL FIND_CLOSED_ORBIT( FIX,LATTICE,1)
WRITE(6,*) FIX(1:2)
! INITIALIZE THE RAY AS  --> 
!RAY = FIXED POINT + IDENTITY (TAYLOR MAP)
ID=1
R=FIX+ID 

!  COMPUTING A ONE-TURN MAP TO ORDER MY_ORDER

CALL TRACK_LATTICE( R,LATTICE,1,1)
M=R    
call print_my_map2( M,mfi=MFM,title=  " The one-turn map :  x  and  p ")

! NORMALIZING THE MAP
CALL NORMALISE(M,NORMAL)   
A_CS=NORMAL%A_T
M=NORMAL%disp**(-1)*M*NORMAL%disp
call print_my_map2( M,NORMAL%disp,mfi=MFM,title=  "  M=NORMAL%disp**(-1)*M*NORMAL%disp   and   NORMAL%disp")
M=NORMAL%A_L**(-1)*M*NORMAL%A_L
call print_my_map2( M,NORMAL%A_L,mfi=MFM,title=  "  M=NORMAL%A_L**(-1)*M*NORMAL%A_L    and   NORMAL%A_L  ")
M=NORMAL%A_NL**(-1)*M*NORMAL%A_NL
call print_my_map2( M,NORMAL%A_NL,mfi=MFM,title=  "  M=NORMAL%A_NL**(-1)*M*NORMAL%A_NL    and   NORMAL%A_NL  ")
CALL print(NORMAL%total_tune,mfi=MFM,TITLE = "TOTAL TUNE ")
X=cos(twopi*NORMAL%total_tune)*dx_1 +sin(twopi*NORMAL%total_tune)*dx_2  
call print_my_taylor2( M%v(1),x,mfi=MFM,title=  "   Comparing normalised map and cos(mu)x+sin(mu)p   ")

j1=0;j1(1)=1;j2=0;j2(2)=1;
beta=((NORMAL%A_L%v(1).par.j1)**2+(NORMAL%A_L%v(1).par.j2)**2).cut.ORDER_OF_TAYLOR%i
call print( beta,mfi=MFM,title=  "   Beta as a function of delta  ")
j1=0;j1(1)=1;j2=0;j2(2)=1;
gamma=((NORMAL%A_L%v(2).par.j1)**2+(NORMAL%A_L%v(2).par.j2)**2).cut.ORDER_OF_TAYLOR%i
call print( gamma,mfi=MFM,title=  "   Gamma as a function of delta  ")
j1=0;j1(1)=1;j2=0;j2(2)=1;
alpha=-((NORMAL%A_L%v(1).par.j1)*(NORMAL%A_L%v(2).par.j1)+(NORMAL%A_L%v(1).par.j2)*(NORMAL%A_L%v(2).par.j2)).cut.ORDER_OF_TAYLOR%i
call print( alpha,mfi=MFM,title=  "   Alpha as a function of delta  ")

ct=(beta*gamma-alpha**2).cut.ORDER_OF_TAYLOR%i
call print( ct,mfi=MFM,title=  "   beta*gamma-alpha**2 as a function of delta  ")

X2_AVERAGE=dx_1**2
call AVERAGE(X2_AVERAGE,a_cs,X2_AVERAGE)
call print(X2_AVERAGE,mfi=MFM,title=" Average of x2 around (0,0,0) ")

id=NORMAL%A_L*NORMAL%A_NL
X2_AVERAGE=dx_1**2
call AVERAGE(X2_AVERAGE,id,X2_AVERAGE)
call print(X2_AVERAGE,mfi=MFM,title=" Average of x2 around eta(delta) ")

call CANONISE(NORMAL%a_t,a_cs,disp,a_l,a_nl)
id=A_L*A_NL
X2_AVERAGE=dx_1**2
call AVERAGE(X2_AVERAGE,id,X2_AVERAGE)
call print(X2_AVERAGE,mfi=MFM,title=" Average of x2 around eta(delta) ")

X=FIX(1)+ DX_1
CALL AVERAGE(X,A_CS,X_AVERAGE)
WRITE(6,*) " NON-LINEAR DISPERSION DEFINED AS <X> = D<X>/DJ * J +  ..."
WRITE(6,*) " TAYLOR MAP RESULTS FOR <X> = D<X>/DJ * J +  ..."
CALL PRINT(X_AVERAGE,TITLE=" <X> FROM MAP NORMAL FORM")
id=1
id%v(1)=2.0_dp*id%v(1)
X_AVERAGE=X_AVERAGE*ID
CALL PRINT(X_AVERAGE,TITLE=" <X> FROM MAP NORMAL FORM IN TERMS OF J")

!!!!!   TRACK LATTICE FUNCTIONS !!!!

!! CANONIZE FORCES THE TRANSFORMATION INTO A SPECIAL FORM
! THE LINEAR PART IS IN COURANT-SNYDER FORM A_12=0 INCLUDING
! PARAMETERS.


  ! INITIALIZE THE RAY AS --> RAY = FIXED POINT + A
  CALL CANONISE( NORMAL%A_T ,A_CS )
  R=FIX+A_CS

  PHASE_ADVANCE=0.0_DP;DX_AVERAGE_DJ=0.0_DP; 

BETAX=(A_CS%V(1).INDEX.1)**2+(A_CS%V(1).INDEX.2)**2
ALPHAX=-((A_CS%V(1).INDEX.1)*(A_CS%V(2).INDEX.1)+(A_CS%V(1).INDEX.2)*(A_CS%V(2).INDEX.2))

WRITE(MF,'(A3,5(1X,E20.13))') "INI",REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,0))), &
REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,1))),REAL(PHASE_ADVANCE%A(SUB_INDEX(2,0,0))),BETAX,ALPHAX

DO J=1,SIZE(LATTICE)

CALL TRACK_MAGNET( R,LATTICE(J) )

 A_TRACKED=R
 FIX=R
 CALL CANONISE(A_TRACKED,A_2,PHASE_ADVANCE0=PHASE_ADVANCE)
 R=FIX+A_2

BETAX=(A_2%V(1).INDEX.1)**2+(A_2%V(1).INDEX.2)**2
ALPHAX=-((A_2%V(1).INDEX.1)*(A_2%V(2).INDEX.1)+(A_2%V(1).INDEX.2)*(A_2%V(2).INDEX.2))
WRITE(MF,'(A3,5(1X,E20.13))') LATTICE(J)%NAME(1:3),REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,0))), &
REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,1))),REAL(PHASE_ADVANCE%A(SUB_INDEX(2,0,0))),BETAX,ALPHAX
 
DX_AVERAGE_DJ=(BETAX)**1.5_DP*LATTICE(J)%bn(ptc_def+2)/4.0_DP &
*(-SIN(PHASE_ADVANCE*TWOPI)+SIN((PHASE_ADVANCE-NORMAL%TUNE)*TWOPI)) &
/(1.0_DP-COS(NORMAL%TUNE*TWOPI)) + DX_AVERAGE_DJ

ENDDO
 
DX_AVERAGE_DJ=DX_AVERAGE_DJ*SQRT(BETAX)

WRITE(6,*) " "
WRITE(6,'(A10,E20.13,A20)') '  D<X>/DJ ', DX_AVERAGE_DJ, " < ---- ANALYTICAL  "  
!  NON-LINEAR DISPERSION DEFINED AS <X> = D<X>/DJ * J +  ...

WRITE(6,*) " "
CALL PRINT(NORMAL%TOTAL_TUNE,TITLE="TUNE FROM ONE TURN MAP")

 WRITE(MF,'(A3,5(1X,E20.13))') "END",REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,0))), &
    REAL(PHASE_ADVANCE%A(SUB_INDEX(0,0,1))),REAL(PHASE_ADVANCE%A(SUB_INDEX(2,0,0))),BETAX,ALPHAX
 WRITE(MF,'(A4,6X,A7,7X,3X,A15,3X,4X,A14,9X,A10,9X,A11)')  &
"NAME", "PHASE_X", "DPHASE_X/DDELTA","DPHASE_X/DR2_X","   BETA   ","   GAMMA   "
 WRITE(MF,*) " "
CALL PRINT(NORMAL%TOTAL_TUNE,MF,TITLE="TUNE FROM ONE TURN MAP")

CALL PRINT(PHASE_ADVANCE,TITLE=" TOTAL NONLINEAR PHASE ADVANCE")
CLOSE(MF)
CLOSE(MFM)
 

END PROGRAM SMALL_CODE_TWISS


